name: ROS 2 Jazzy CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS 2 Jazzy
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Install dependencies
        run: |
          sudo apt update
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y

      - name: Force Clean Build Artifacts
        run: |
          # テスト前に古いゴミを強制的に消去する
          rm -rf build/
          rm -rf install/
          rm -rf log/

      - name: Build
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --event-handlers console_direct+

      - name: Test
        run: |
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          # buildとinstallフォルダをチェック対象から外してテスト実行
          colcon test --event-handlers console_direct+ --pytest-args "--flake8 --ignore=build --ignore=install"

      - name: Test result
        if: always()
        run: |
          colcon test-result --verbose
